### ISSUE TITLE
Wrong camera key for the watchtowers

### ISSUE THREAD

**Issue by afdaniele** [duckietown/dt-gui-tools#48]
If I create a map with one vehicle and one watchtower, this is what I get in the YAML file for the `cameras` layer.

```
cameras:
  map_1/vehicle_576/camera:
    camera_matrix: ~
    distortion_parameters: ~
    width: 0
    height: 0
    framerate: 0
  map_1/watchtower_901/camera_932:
    camera_matrix: ~
    distortion_parameters: ~
    width: 0
    height: 0
    framerate: 0
```

While the vehicle has the camera key ending with `.../camera`, the watchtower has the camera key `.../camera_932`.
Remove the random number `932` from the camera key.
